"""Curated catalogue of real-world technology products used for database seeding."""

from __future__ import annotations

PRODUCT_CATALOG: list[dict[str, object]] = [
    {
        "sku": "GPU-RTX4070TI-SUPER-FE",
        "name": "GeForce RTX 4070 Ti SUPER Founders Edition",
        "brand": "NVIDIA",
        "category": "PC Components",
        "price_aud": 1499.0,
        "inventory": 18,
        "description": "NVIDIA's Ada Lovelace flagship for 4K creators with 16GB of GDDR6X memory, 285W TGP, and dual axial flow cooling tuned by the Founders Edition shroud.",
        "image_path": "img/products/nvidia-geforce-rtx4070ti-super.jpg",
        "product_url": "https://www.nvidia.com/en-au/geforce/graphics-cards/40-series/rtx-4070-ti-super/",
    },
    {
        "sku": "GPU-RTX4080-SUPER-FE",
        "name": "GeForce RTX 4080 SUPER Founders Edition",
        "brand": "NVIDIA",
        "category": "PC Components",
        "price_aud": 1999.0,
        "inventory": 12,
        "description": "32-bit Shader Execution Reordering and DLSS 3.5 power this 16GB Ada GPU with 52 Shader TFLOPS and a triple-slot vapor chamber cooler for sustained 4K/120 performance.",
        "image_path": "img/products/nvidia-geforce-rtx4080-super.jpg",
        "product_url": "https://www.nvidia.com/en-au/geforce/graphics-cards/40-series/rtx-4080-super/",
    },
    {
        "sku": "GPU-RX7800XT-NITROPLUS",
        "name": "Radeon RX 7800 XT NITRO+ OC",
        "brand": "Sapphire",
        "category": "PC Components",
        "price_aud": 1099.0,
        "inventory": 22,
        "description": "Sapphire's triple-fan Nitro+ cooler keeps the 16GB RDNA 3 GPU quiet while dual BIOS, digital VRM monitoring, and HDMI 2.1/DisplayPort 2.1 outputs suit 1440p esports rigs.",
        "image_path": "img/products/sapphire-rx7800xt-nitroplus.jpg",
        "product_url": "https://www.sapphiretech.com/en/consumer/nitro-radeon-rx-7800-xt-oc-16g-gddr6",
    },
    {
        "sku": "CPU-RYZEN7-7800X3D",
        "name": "Ryzen 7 7800X3D",
        "brand": "AMD",
        "category": "PC Components",
        "price_aud": 699.0,
        "inventory": 34,
        "description": "8 Zen 4 cores, 16 threads, and 96MB of 3D V-Cache deliver chart-topping gaming latency on AM5 along with PCIe 5.0 lanes and DDR5-6000 EXPO support.",
        "image_path": "img/products/amd-ryzen-7-7800x3d.jpg",
        "product_url": "https://www.amd.com/en/products/processors/desktop/ryzen/7000/amd-ryzen-7-7800x3d",
    },
    {
        "sku": "CPU-I7-14700K",
        "name": "Core i7-14700K",
        "brand": "Intel",
        "category": "PC Components",
        "price_aud": 799.0,
        "inventory": 29,
        "description": "20 cores (8P + 12E) and 33MB of Intel Smart Cache push up to 5.6GHz with Intel Thread Director, supporting DDR5-5600 and PCIe 5.0 lanes on LGA1700 boards.",
        "image_path": "img/products/intel-core-i7-14700k.jpg",
        "product_url": "https://www.intel.com/content/www/us/en/products/sku/236847/intel-core-i714700k-processor-33m-cache-up-to-5-60-ghz/specifications.html",
    },
    {
        "sku": "CPU-I5-13600K",
        "name": "Core i5-13600K",
        "brand": "Intel",
        "category": "PC Components",
        "price_aud": 499.0,
        "inventory": 37,
        "description": "A 14-core hybrid design pairs 6 P-cores with 8 E-cores, giving creators PCIe 5.0, DDR5/DDR4 flexibility, and an unlocked multiplier for compact gaming builds.",
        "image_path": "img/products/intel-core-i5-13600k.jpg",
        "product_url": "https://www.intel.com/content/www/us/en/products/sku/230500/intel-core-i513600k-processor-24m-cache-up-to-5-10-ghz/specifications.html",
    },
    {
        "sku": "MB-ASUS-Z790E-II",
        "name": "ROG Strix Z790-E Gaming WiFi II",
        "brand": "ASUS",
        "category": "PC Components",
        "price_aud": 969.0,
        "inventory": 16,
        "description": "18+2 teamed power stages, PCIe 5.0 x16, five M.2 slots, and Wi-Fi 7 radios anchor this flagship ATX board with Q-Release PCIe and Q-Latch storage tooling.",
        "image_path": "img/products/asus-rog-strix-z790e-gaming-wifi-ii.jpg",
        "product_url": "https://rog.asus.com/motherboards/rog-strix/rog-strix-z790-e-gaming-wifi-ii-model/",
    },
    {
        "sku": "MB-MSI-B650-TOMAHAWK",
        "name": "MAG B650 Tomahawk WiFi",
        "brand": "MSI",
        "category": "PC Components",
        "price_aud": 459.0,
        "inventory": 41,
        "description": "An AM5 mid-tower staple with 14+2+1 duet rail power, PCIe 5.0 M.2 slot, 2.5G LAN, Wi-Fi 6E, and BIOS Flashback for painless Ryzen 7000 deployments.",
        "image_path": "img/products/msi-mag-b650-tomahawk-wifi.jpg",
        "product_url": "https://www.msi.com/Motherboard/MAG-B650-TOMAHAWK-WIFI",
    },
    {
        "sku": "MB-GIGABYTE-X670E-AORUS-MASTER",
        "name": "X670E AORUS Master",
        "brand": "Gigabyte",
        "category": "PC Components",
        "price_aud": 899.0,
        "inventory": 14,
        "description": "A finned VRM heatsink keeps the 16-phase design cool while twin PCIe 5.0 x16 slots, PCIe 5.0 M.2, and Wi-Fi 6E ready this board for Threadripper-class workloads.",
        "image_path": "img/products/gigabyte-x670e-aorus-master.jpg",
        "product_url": "https://www.gigabyte.com/Motherboard/X670E-AORUS-MASTER-rev-10",
    },
    {
        "sku": "MB-ASROCK-B760M-STEEL",
        "name": "B760M Steel Legend WiFi",
        "brand": "ASRock",
        "category": "PC Components",
        "price_aud": 329.0,
        "inventory": 44,
        "description": "Matte camo styling meets 12+1+1 power stages, PCIe 5.0 x16, dual Gen4 M.2 slots, and Wi-Fi 6E for mainstream 14th Gen gaming rigs.",
        "image_path": "img/products/asrock-b760m-steel-legend-wifi.jpg",
        "product_url": "https://www.asrock.com/mb/Intel/B760M%20Steel%20Legend%20WiFi/index.asp",
    },
    {
        "sku": "SSD-SAMSUNG-990PRO-2TB",
        "name": "990 PRO NVMe SSD 2TB",
        "brand": "Samsung",
        "category": "PC Components",
        "price_aud": 329.0,
        "inventory": 65,
        "description": "PCIe 4.0 x4 throughput up to 7,450MB/s with Samsung's nickel-plated controller, Dynamic Thermal Guard, and Magician firmware for sustained workstation loads.",
        "image_path": "img/products/samsung-990-pro-2tb.jpg",
        "product_url": "https://www.samsung.com/au/memory-storage/ssd/990-pro-nvme-m2-2280-2tb-mz-v9p2t0bw/",
    },
    {
        "sku": "SSD-WD-SN850X-1TB",
        "name": "WD_BLACK SN850X 1TB NVMe SSD",
        "brand": "Western Digital",
        "category": "PC Components",
        "price_aud": 219.0,
        "inventory": 72,
        "description": "Western Digital's PCIe 4.0 flagship hits 7,300MB/s reads with a DRAM cache, Game Mode 2.0 firmware, and optional heatsink for PS5 or compact PC installs.",
        "image_path": "img/products/wd-black-sn850x-1tb.jpg",
        "product_url": "https://www.westerndigital.com/en-au/products/internal-drives/wd-black-sn850x-nvme-ssd",
    },
    {
        "sku": "SSD-CRUCIAL-T700-2TB",
        "name": "Crucial T700 2TB PCIe Gen5 SSD",
        "brand": "Crucial",
        "category": "PC Components",
        "price_aud": 559.0,
        "inventory": 27,
        "description": "Gen5 x4 horsepower hits 12,400MB/s reads with a chunky passive heatsink, DirectStorage-ready firmware, and Micron 232-layer TLC NAND.",
        "image_path": "img/products/crucial-t700-2tb.jpg",
        "product_url": "https://www.crucial.com/products/ssd/t700",
    },
    {
        "sku": "SSD-CORSAIR-MP700-2TB",
        "name": "MP700 2TB PCIe 5.0 NVMe SSD",
        "brand": "Corsair",
        "category": "PC Components",
        "price_aud": 509.0,
        "inventory": 31,
        "description": "A Gen5 controller with 10,000MB/s throughput, full-body heatsink, and Corsair SSD Toolbox support keeps high-end workstations future proof.",
        "image_path": "img/products/corsair-mp700-2tb.jpg",
        "product_url": "https://www.corsair.com/us/en/p/ssd/mp700-gen5-pcie-x4-nvme-1-4-m-2-ssd-2tb-cssd-f2000gbmp700",
    },
    {
        "sku": "RAM-CORSAIR-VENGEANCE-RGB-32",
        "name": "Vengeance RGB DDR5 32GB (2x16GB) 6000MT/s",
        "brand": "Corsair",
        "category": "PC Components",
        "price_aud": 249.0,
        "inventory": 58,
        "description": "Black aluminium heat spreaders, individually addressable RGB, and tight CL36 timings make this EXPO/XMP kit a solid AM5/LGA1700 pairing.",
        "image_path": "img/products/corsair-vengeance-rgb-ddr5-32gb.jpg",
        "product_url": "https://www.corsair.com/us/en/p/memory/cmk32gx5m2b6000c36/vengeance-rgb-32gb-2x16gb-ddr5-dram-6000mhz-c36-memory-kit-black",
    },
    {
        "sku": "RAM-GSKILL-TRIDENT-Z5-NEO",
        "name": "Trident Z5 Neo RGB DDR5 32GB 6000 CL30",
        "brand": "G.Skill",
        "category": "PC Components",
        "price_aud": 319.0,
        "inventory": 33,
        "description": "Optimised for AMD EXPO, this dual-rank kit pairs matte black heatsinks with CL30 timings for stable 6000MT/s Infinity Fabric sync.",
        "image_path": "img/products/gskill-trident-z5-neo-rgb.jpg",
        "product_url": "https://www.gskill.com/product/165/374/1663836408/F5-6000J3038F16GX2-TZ5NR",
    },
    {
        "sku": "RAM-KINGSTON-FURY-BEAST-64",
        "name": "FURY Beast DDR5 64GB (2x32GB) 5600MT/s",
        "brand": "Kingston",
        "category": "PC Components",
        "price_aud": 359.0,
        "inventory": 25,
        "description": "High-density UDIMMs with Plug N Play 5600MT/s timings, on-die ECC, and low-profile heat spreaders for compact workstations.",
        "image_path": "img/products/kingston-fury-beast-ddr5-64gb.jpg",
        "product_url": "https://www.kingston.com/en/memory/gaming/kingston-fury-beast-ddr5",
    },
    {
        "sku": "PSU-SEASONIC-PRIME-TX-1000",
        "name": "Prime TX-1000 80+ Titanium",
        "brand": "Seasonic",
        "category": "PC Components",
        "price_aud": 449.0,
        "inventory": 19,
        "description": "A flagship 1000W platform with 80+ Titanium efficiency, Micro Tolerance Load Regulation, and hybrid fan control for silent high-end builds.",
        "image_path": "img/products/seasonic-prime-tx-1000.jpg",
        "product_url": "https://seasonic.com/prime-tx",
    },
    {
        "sku": "PSU-CORSAIR-RM850E-2023",
        "name": "RM850e (2023) Fully Modular PSU",
        "brand": "Corsair",
        "category": "PC Components",
        "price_aud": 239.0,
        "inventory": 54,
        "description": "ATX 3.0-ready cabling with a native 12VHPWR lead, 80+ Gold efficiency, and a compact 140mm chassis suits mainstream RTX 40-Series rigs.",
        "image_path": "img/products/corsair-rm850e-psu.jpg",
        "product_url": "https://www.corsair.com/us/en/p/psu/cp-9020263-na/rm850e-fully-modular-low-noise-atx-power-supply",
    },
    {
        "sku": "COOLER-NOCTUA-NH-D15-CHROMAX",
        "name": "NH-D15 chromax.black",
        "brand": "Noctua",
        "category": "PC Components",
        "price_aud": 169.0,
        "inventory": 47,
        "description": "Dual NF-A15 PWM fans, a massive dual-tower array, and SecuFirm2 mounting keep 230W CPUs chilled without liquid cooling complexity.",
        "image_path": "img/products/noctua-nh-d15-chromax-black.jpg",
        "product_url": "https://noctua.at/en/nh-d15-chromax-black",
    },
    {
        "sku": "SBC-RPI5-8GB",
        "name": "Raspberry Pi 5 (8GB)",
        "brand": "Raspberry Pi",
        "category": "Microcontrollers & SBCs",
        "price_aud": 159.0,
        "inventory": 90,
        "description": "A 16nm quad-core Cortex-A76 SoC with dual 4K60 HDMI, PCIe 2.0 x1 FPC, and a reworked power design that finally brings USB-C PD to the Pi ecosystem.",
        "image_path": "img/products/raspberry-pi-5-8gb.jpg",
        "product_url": "https://www.raspberrypi.com/products/raspberry-pi-5/",
    },
    {
        "sku": "SBC-RPI4-8GB",
        "name": "Raspberry Pi 4 Model B (8GB)",
        "brand": "Raspberry Pi",
        "category": "Microcontrollers & SBCs",
        "price_aud": 129.0,
        "inventory": 140,
        "description": "Broadcom's quad-core Cortex-A72 board with dual micro HDMI, true gigabit Ethernet, onboard Wi-Fi, and 8GB LPDDR4 for headless servers or signage.",
        "image_path": "img/products/raspberry-pi-4-8gb.jpg",
        "product_url": "https://www.raspberrypi.com/products/raspberry-pi-4-model-b/",
    },
    {
        "sku": "MCU-RPI-PICO-W",
        "name": "Raspberry Pi Pico W",
        "brand": "Raspberry Pi",
        "category": "Microcontrollers & SBCs",
        "price_aud": 12.0,
        "inventory": 320,
        "description": "RP2040 dual-core microcontroller with 2MB flash, onboard Infineon Wi-Fi, and castellated edges for embedding MicroPython into connected gadgets.",
        "image_path": "img/products/raspberry-pi-pico-w.jpg",
        "product_url": "https://www.raspberrypi.com/products/raspberry-pi-pico-w/",
    },
    {
        "sku": "MCU-ARDUINO-UNO-R4WIFI",
        "name": "Arduino UNO R4 WiFi",
        "brand": "Arduino",
        "category": "Microcontrollers & SBCs",
        "price_aud": 109.0,
        "inventory": 85,
        "description": "Renesas RA4M1 Arm Cortex-M4 core, 256KB flash, built-in ESP32-S3 Wi-Fi/BLE coprocessor, and a bright 12x8 LED matrix modernise the classic UNO footprint.",
        "image_path": "img/products/arduino-uno-r4-wifi.jpg",
        "product_url": "https://store.arduino.cc/products/uno-r4-wifi",
    },
    {
        "sku": "MCU-ARDUINO-MEGA2560",
        "name": "Arduino Mega 2560 Rev3",
        "brand": "Arduino",
        "category": "Microcontrollers & SBCs",
        "price_aud": 69.0,
        "inventory": 110,
        "description": "ATmega2560 with 54 digital I/O, 16 analog inputs, and four hardware UARTs remains the go-to board for CNC, robotics, and multi-sensor projects.",
        "image_path": "img/products/arduino-mega-2560.jpg",
        "product_url": "https://store.arduino.cc/products/mega-2560-rev3",
    },
    {
        "sku": "MCU-ARDUINO-PORTENTA-H7L",
        "name": "Arduino Portenta H7 Lite",
        "brand": "Arduino",
        "category": "Microcontrollers & SBCs",
        "price_aud": 189.0,
        "inventory": 42,
        "description": "Dual-core STM32H747 (M7+M4), on-board crypto, and high-speed edge connectors deliver industrial IoT power for custom carrier boards.",
        "image_path": "img/products/arduino-portenta-h7-lite.jpg",
        "product_url": "https://store.arduino.cc/products/portenta-h7-lite",
    },
    {
        "sku": "MCU-ADAFRUIT-FEATHER-RP2040",
        "name": "Adafruit Feather RP2040",
        "brand": "Adafruit",
        "category": "Microcontrollers & SBCs",
        "price_aud": 29.0,
        "inventory": 210,
        "description": "The RP2040 with 264KB SRAM joins the Feather ecosystem with LiPo charging, STEMMA QT connector, and native USB for CircuitPython.",
        "image_path": "img/products/adafruit-feather-rp2040.jpg",
        "product_url": "https://www.adafruit.com/product/4884",
    },
    {
        "sku": "MCU-ADAFRUIT-METRO-M4",
        "name": "Adafruit Metro M4 Express (SAMD51)",
        "brand": "Adafruit",
        "category": "Microcontrollers & SBCs",
        "price_aud": 49.0,
        "inventory": 95,
        "description": "A 120MHz Cortex-M4F with 512KB flash, native USB, and Feather-compatible headers for CircuitPython prototyping at higher clock speeds.",
        "image_path": "img/products/adafruit-metro-m4-express.jpg",
        "product_url": "https://www.adafruit.com/product/3382",
    },
    {
        "sku": "MCU-SPARKFUN-ARTEMIS-NANO",
        "name": "SparkFun RedBoard Artemis Nano",
        "brand": "SparkFun",
        "category": "Microcontrollers & SBCs",
        "price_aud": 42.0,
        "inventory": 120,
        "description": "Ambiq Apollo3 Blue MCU with BLE 5.0, ultra-low-power modes, and Qwiic connector ready for battery-powered sensor nodes.",
        "image_path": "img/products/sparkfun-artemis-nano.jpg",
        "product_url": "https://www.sparkfun.com/products/15444",
    },
    {
        "sku": "MCU-TEENSY-41",
        "name": "Teensy 4.1",
        "brand": "PJRC",
        "category": "Microcontrollers & SBCs",
        "price_aud": 54.0,
        "inventory": 88,
        "description": "A 600MHz Cortex-M7, 8MB flash, and Ethernet/QSPI pads make Teensy 4.1 a powerhouse for real-time DSP and custom control surfaces.",
        "image_path": "img/products/teensy-4-1.jpg",
        "product_url": "https://www.pjrc.com/store/teensy41.html",
    },
    {
        "sku": "MCU-ESP32-DEVKITC",
        "name": "ESP32-WROOM-32 DevKitC V4",
        "brand": "Espressif",
        "category": "Microcontrollers & SBCs",
        "price_aud": 21.0,
        "inventory": 260,
        "description": "Dual-core Xtensa MCU with Wi-Fi and BLE, castellated pins, and native USB-UART for pairing with ESP-IDF or Arduino frameworks.",
        "image_path": "img/products/espressif-esp32-devkitc.jpg",
        "product_url": "https://www.espressif.com/en/products/devkits/esp32-devkitc",
    },
    {
        "sku": "MCU-XIAO-ESP32C3",
        "name": "Seeed Studio XIAO ESP32C3",
        "brand": "Seeed Studio",
        "category": "Microcontrollers & SBCs",
        "price_aud": 18.0,
        "inventory": 240,
        "description": "A thumbnail-sized RISC-V Wi-Fi/BLE module with USB-C, 11 GPIO, and low-power deep sleep for wearables and tiny ML nodes.",
        "image_path": "img/products/seeed-xiao-esp32c3.jpg",
        "product_url": "https://www.seeedstudio.com/XIAO-ESP32C3-p-5438.html",
    },
    {
        "sku": "MCU-PARTICLE-BORON-LTE",
        "name": "Particle Boron LTE Kit",
        "brand": "Particle",
        "category": "Microcontrollers & SBCs",
        "price_aud": 133.0,
        "inventory": 52,
        "description": "Nordic nRF52840 with LTE Cat-M1/NB-IoT modem, eSIM, and Particle Device OS for secure cloud-connected monitoring nodes.",
        "image_path": "img/products/particle-boron-lte.jpg",
        "product_url": "https://store.particle.io/products/boron-lte",
    },
    {
        "sku": "SBC-BEAGLEBONE-BLACK",
        "name": "BeagleBone Black Rev C",
        "brand": "BeagleBoard.org",
        "category": "Microcontrollers & SBCs",
        "price_aud": 99.0,
        "inventory": 67,
        "description": "TI Sitara AM335x with 65 GPIO, PRU real-time cores, onboard eMMC, and full-size HDMI for industrial control projects.",
        "image_path": "img/products/beaglebone-black-revc.jpg",
        "product_url": "https://www.beagleboard.org/boards/beaglebone-black",
    },
    {
        "sku": "SBC-JETSON-ORIN-NANO",
        "name": "Jetson Orin Nano Developer Kit",
        "brand": "NVIDIA",
        "category": "Microcontrollers & SBCs",
        "price_aud": 599.0,
        "inventory": 23,
        "description": "A 1024-core Ampere GPU with 32 Tensor Cores, 6-core Arm CPU, and 8GB LPDDR5 memory for edge AI robotics and vision stacks.",
        "image_path": "img/products/nvidia-jetson-orin-nano-devkit.jpg",
        "product_url": "https://developer.nvidia.com/embedded/jetson-orin-nano-dev-kit",
    },
    {
        "sku": "ROBO-INTEL-D455",
        "name": "RealSense Depth Camera D455",
        "brand": "Intel RealSense",
        "category": "Robotics",
        "price_aud": 569.0,
        "inventory": 28,
        "description": "Improved baseline stereo depth with a 95mm spacing, global shutter sensors, and an IMU lets mobile robots see accurate depth up to 20 metres indoors or out.",
        "image_path": "img/products/intel-realsense-d455.jpg",
        "product_url": "https://www.intelrealsense.com/depth-camera-d455/",
    },
    {
        "sku": "ROBO-LUXONIS-OAKD-LITE",
        "name": "Luxonis OAK-D Lite",
        "brand": "Luxonis",
        "category": "Robotics",
        "price_aud": 249.0,
        "inventory": 46,
        "description": "Myriad X VPU with onboard depth fusion and USB-C connectivity lets ROS nodes stream 4K color plus 400k-point depth without taxing the host CPU.",
        "image_path": "img/products/luxonis-oak-d-lite.jpg",
        "product_url": "https://shop.luxonis.com/products/oak-d-lite",
    },
    {
        "sku": "ROBO-DYNAMIXEL-XM430-W210",
        "name": "DYNAMIXEL XM430-W210-T",
        "brand": "ROBOTIS",
        "category": "Robotics",
        "price_aud": 699.0,
        "inventory": 17,
        "description": "A smart servo with 360° position control, 4.1 Nm stall torque, and TTL daisy-chaining for articulated arms and humanoid projects.",
        "image_path": "img/products/dynamixel-xm430-w210-t.jpg",
        "product_url": "https://emanual.robotis.com/docs/en/dxl/x/xm430-w210/",
    },
    {
        "sku": "ROBO-GOBILDA-5202-19",
        "name": "5202 Series Yellow Jacket 19.2:1 Gearmotor",
        "brand": "goBILDA",
        "category": "Robotics",
        "price_aud": 142.0,
        "inventory": 63,
        "description": "A 435 RPM spur-geared DC motor with 3.3V quadrature encoder and 8mm REX shaft mates natively with goBILDA channel builds.",
        "image_path": "img/products/gobilda-5202-yellow-jacket.jpg",
        "product_url": "https://www.gobilda.com/5202-series-yellow-jacket-planetary-gear-motor-19-2-1-ratio-24mm-length-8mm-rex-shaft-435-rpm-3-3-5v-encoder/",
    },
    {
        "sku": "ROBO-REV-NEO-VORTEX",
        "name": "NEO Vortex Brushless Motor",
        "brand": "REV Robotics",
        "category": "Robotics",
        "price_aud": 429.0,
        "inventory": 21,
        "description": "REV's latest FOC-friendly brushless motor outputs 2.6Nm stall torque with an integrated temperature sensor and keyed 8mm shaft for FRC drivetrains.",
        "image_path": "img/products/rev-neo-vortex.jpg",
        "product_url": "https://www.revrobotics.com/rev-21-1652/",
    },
    {
        "sku": "ROBO-TMOTOR-U8PRO-KV135",
        "name": "T-Motor U8 Pro KV135",
        "brand": "T-Motor",
        "category": "Robotics",
        "price_aud": 469.0,
        "inventory": 18,
        "description": "A 135KV pancake outrunner designed for heavy-lift UAVs, featuring AS2308 bearings and up to 2.6kg of thrust per rotor on 12S LiPo packs.",
        "image_path": "img/products/tmotor-u8-pro-kv135.jpg",
        "product_url": "https://store.tmotor.com/goods-617-T-MOTOR+U8+PRO+KV135.html",
    },
    {
        "sku": "ROBO-ODRIVE-S1",
        "name": "ODrive S1 Motor Controller",
        "brand": "ODrive Robotics",
        "category": "Robotics",
        "price_aud": 389.0,
        "inventory": 32,
        "description": "High-voltage FOC controller that drives two BLDC motors at up to 60V, 100A with USB-C, CAN, and encoder feedback for hobby to research robots.",
        "image_path": "img/products/odrive-s1-controller.jpg",
        "product_url": "https://odriverobotics.com/shop/odrive-s1",
    },
    {
        "sku": "ROBO-BENEWAKE-TFMINIS",
        "name": "Benewake TFmini-S LiDAR Module",
        "brand": "Benewake",
        "category": "Robotics",
        "price_aud": 69.0,
        "inventory": 120,
        "description": "A 12-meter single-point LiDAR with 1cm accuracy, UART/I2C outputs, and IP65 housing for obstacle detection on bots and drones.",
        "image_path": "img/products/benewake-tfmini-s.jpg",
        "product_url": "https://www.benewake.com/en/tfmini-s.html",
    },
    {
        "sku": "ROBO-HOKUYO-UST10LX",
        "name": "Hokuyo UST-10LX Scanning LiDAR",
        "brand": "Hokuyo",
        "category": "Robotics",
        "price_aud": 1995.0,
        "inventory": 6,
        "description": "270° field of view, 40Hz update rate, and 10m range with Ethernet output make it a proven 2D LiDAR for SLAM and safety monitoring.",
        "image_path": "img/products/hokuyo-ust-10lx.jpg",
        "product_url": "https://www.hokuyo-aut.jp/search/single.php?serial=169",
    },
    {
        "sku": "ROBO-SPARKFUN-RTK-EXPRESS",
        "name": "SparkFun RTK Express Kit",
        "brand": "SparkFun",
        "category": "Robotics",
        "price_aud": 799.0,
        "inventory": 14,
        "description": "u-blox ZED-F9P multi-band GNSS with Bluetooth, OLED interface, and built-in battery delivers centimeter-grade positioning for rovers.",
        "image_path": "img/products/sparkfun-rtk-express.jpg",
        "product_url": "https://www.sparkfun.com/products/20065",
    },
    {
        "sku": "CBL-BELKIN-HDMI21-2M",
        "name": "Ultra High Speed HDMI 2.1 Cable (2m)",
        "brand": "Belkin",
        "category": "Cables & Adapters",
        "price_aud": 49.0,
        "inventory": 180,
        "description": "Certified 48Gbps HDMI cable with full 8K60 / 4K120 bandwidth, eARC, and Belkin's braided jacket for rigging VR headsets and consoles.",
        "image_path": "img/products/belkin-ultra-hdmi-21-2m.jpg",
        "product_url": "https://www.belkin.com/au/ultra-hdmi-2.1-cable-2m/P-AV10175bt2M-BLK.html",
    },
    {
        "sku": "CBL-ANKER-555-HUB",
        "name": "Anker 555 USB-C Hub (8-in-1)",
        "brand": "Anker",
        "category": "Cables & Adapters",
        "price_aud": 129.0,
        "inventory": 75,
        "description": "Adds dual HDMI, Gigabit Ethernet, SD/MicroSD, and 100W pass-through for USB-C laptops needing a single-cable desk dock.",
        "image_path": "img/products/anker-555-usbc-hub.jpg",
        "product_url": "https://www.anker.com/products/a8381",
    },
    {
        "sku": "CBL-CABLEMATTERS-USB4-1M",
        "name": "Cable Matters USB4 20Gbps Cable (1m)",
        "brand": "Cable Matters",
        "category": "Cables & Adapters",
        "price_aud": 39.0,
        "inventory": 140,
        "description": "USB4 / Thunderbolt 3 compatible cable certified for 20Gbps data, 100W PD, and DisplayPort Alt Mode for high-speed dev kits.",
        "image_path": "img/products/cable-matters-usb4-cable.jpg",
        "product_url": "https://www.cablematters.com/pc-1529-146-usb4-cable-20gbps.aspx",
    },
    {
        "sku": "CBL-APPLE-USBC-AV",
        "name": "USB-C Digital AV Multiport Adapter",
        "brand": "Apple",
        "category": "Cables & Adapters",
        "price_aud": 109.0,
        "inventory": 98,
        "description": "Adds HDMI 2.0, USB-A, and pass-through USB-C for iPad Pro, MacBook, and USB-C dev boards using a single dongle.",
        "image_path": "img/products/apple-usbc-digital-av-adapter.jpg",
        "product_url": "https://www.apple.com/au/shop/product/MUF82AM/A/usb-c-digital-av-multiport-adapter",
    },
    {
        "sku": "CBL-UGREEN-USBC-ETH",
        "name": "UGREEN USB-C to Gigabit Ethernet Adapter",
        "brand": "UGREEN",
        "category": "Cables & Adapters",
        "price_aud": 44.0,
        "inventory": 160,
        "description": "A compact aluminum adapter with Realtek RTL8153 chipset for plugging USB-C laptops or SBCs into wired lab networks.",
        "image_path": "img/products/ugreen-usbc-ethernet.jpg",
        "product_url": "https://www.ugreen.com/products/usb-c-to-ethernet-adapter",
    },
    {
        "sku": "CBL-STARTECH-TB4-08M",
        "name": "StarTech Thunderbolt 4 Cable (0.8m)",
        "brand": "StarTech",
        "category": "Cables & Adapters",
        "price_aud": 89.0,
        "inventory": 64,
        "description": "40Gbps Thunderbolt 4 certified cable rated for 100W Power Delivery and daisy-chaining two 4K displays.",
        "image_path": "img/products/startech-thunderbolt4-cable.jpg",
        "product_url": "https://www.startech.com/en-au/cables/wtb4cm.8in",
    },
    {
        "sku": "CBL-SATECHI-USBC-MULTIPORT",
        "name": "Satechi USB-C Multiport Adapter 4K",
        "brand": "Satechi",
        "category": "Cables & Adapters",
        "price_aud": 149.0,
        "inventory": 58,
        "description": "Machined aluminium hub delivering 4K60 HDMI, USB-A, SD card, and PD passthrough for portable Mac/PC setups.",
        "image_path": "img/products/satechi-usbc-multiport-adapter.jpg",
        "product_url": "https://satechi.net/products/type-c-multiport-adapter-4k-with-ethernet",
    },
    {
        "sku": "CBL-ADAFRUIT-STEMMA-QT-150MM",
        "name": "STEMMA QT / Qwiic Cable with Female Headers",
        "brand": "Adafruit",
        "category": "Cables & Adapters",
        "price_aud": 2.0,
        "inventory": 500,
        "description": "150mm JST-SH cable transitions from STEMMA QT/Qwiic sensors to 0.1\" female headers for breadboard prototyping.",
        "image_path": "img/products/adafruit-stemma-qt-female-cable.jpg",
        "product_url": "https://www.adafruit.com/product/4397",
    },
    {
        "sku": "CBL-SPARKFUN-QWIIC-KIT",
        "name": "SparkFun Qwiic Cable Kit",
        "brand": "SparkFun",
        "category": "Cables & Adapters",
        "price_aud": 18.0,
        "inventory": 130,
        "description": "A pack of JST-SH Qwiic cables in multiple lengths plus breadboard breakout for quickly chaining I2C sensors.",
        "image_path": "img/products/sparkfun-qwiic-cable-kit.jpg",
        "product_url": "https://www.sparkfun.com/products/15082",
    },
    {
        "sku": "CBL-NZXT-INTERNAL-USBHUB-G3",
        "name": "NZXT Internal USB Hub (Gen 3)",
        "brand": "NZXT",
        "category": "Cables & Adapters",
        "price_aud": 69.0,
        "inventory": 77,
        "description": "Adds four internal USB 2.0 headers and a USB-C header powered by SATA for managing AIOs, RGB controllers, and monitors.",
        "image_path": "img/products/nzxt-internal-usb-hub-gen3.jpg",
        "product_url": "https://nzxt.com/product/internal-usb-hub-gen-3",
    },
    {
        "sku": "TOOLS-HAKKO-FX888D",
        "name": "Hakko FX-888D Soldering Station",
        "brand": "Hakko",
        "category": "Tools & Test",
        "price_aud": 199.0,
        "inventory": 58,
        "description": "Digital control, 65W ceramic heater, and T18 tip ecosystem make this the go-to bench iron for lead-free assembly.",
        "image_path": "img/products/hakko-fx888d.jpg",
        "product_url": "https://www.hakko.com/english/products/hakko_fx888d.html",
    },
    {
        "sku": "TOOLS-WELLER-WE1010",
        "name": "Weller WE1010NA Soldering Station",
        "brand": "Weller",
        "category": "Tools & Test",
        "price_aud": 289.0,
        "inventory": 34,
        "description": "A 70W soldering station with ergonomic WEP70 iron, digital readout, and standby timers for educational labs.",
        "image_path": "img/products/weller-we1010na.jpg",
        "product_url": "https://www.weller-tools.com/we1010na",
    },
    {
        "sku": "TOOLS-PINECIL-V2",
        "name": "Pinecil Smart Portable Soldering Iron V2",
        "brand": "Pine64",
        "category": "Tools & Test",
        "price_aud": 89.0,
        "inventory": 112,
        "description": "USB-C PD-powered TS100-style iron with open firmware, OLED display, and 320°C heat in under 30 seconds.",
        "image_path": "img/products/pinecil-v2.jpg",
        "product_url": "https://pine64.com/product/pinecil-smart-mini-portable-soldering-iron-v2/",
    },
    {
        "sku": "TOOLS-IFIXIT-PROTECH",
        "name": "iFixit Pro Tech Toolkit",
        "brand": "iFixit",
        "category": "Tools & Test",
        "price_aud": 119.0,
        "inventory": 150,
        "description": "64 precision bits, spudgers, suction cups, and picks for disassembling laptops, phones, and robotics gear without damage.",
        "image_path": "img/products/ifixit-pro-tech-toolkit.jpg",
        "product_url": "https://www.ifixit.com/products/pro-tech-toolkit",
    },
    {
        "sku": "TOOLS-FLUKE-115",
        "name": "Fluke 115 Digital Multimeter",
        "brand": "Fluke",
        "category": "Tools & Test",
        "price_aud": 329.0,
        "inventory": 43,
        "description": "6000-count backlit DMM with True-RMS, microamp ranges, and CAT III 600V safety rating for field diagnostics.",
        "image_path": "img/products/fluke-115.jpg",
        "product_url": "https://www.fluke.com/en-au/product/electrical-testing/digital-multimeters/fluke-115",
    },
    {
        "sku": "TOOLS-KEYSIGHT-U1232A",
        "name": "Keysight U1232A Handheld Multimeter",
        "brand": "Keysight",
        "category": "Tools & Test",
        "price_aud": 349.0,
        "inventory": 31,
        "description": "10,000-count dual display, ZLOW low-impedance mode, and LED flashlight make it perfect for cramped racks.",
        "image_path": "img/products/keysight-u1232a.jpg",
        "product_url": "https://www.keysight.com/au/en/product/U1232A/handheld-digital-multimeter-10000-count-display.html",
    },
    {
        "sku": "TOOLS-RIGOL-DS1102ZE",
        "name": "Rigol DS1102Z-E 100MHz Oscilloscope",
        "brand": "Rigol",
        "category": "Tools & Test",
        "price_aud": 599.0,
        "inventory": 22,
        "description": "Two-channels at 100MHz bandwidth, 1GSa/s sampling, and 24Mpts memory capture signal anomalies in embedded bring-up.",
        "image_path": "img/products/rigol-ds1102z-e.jpg",
        "product_url": "https://www.rigolna.com/products/digital-oscilloscopes/ds1000z/ds1102z-e/",
    },
    {
        "sku": "TOOLS-HAKKO-CHP170",
        "name": "Hakko CHP-170 Flush Cutter",
        "brand": "Hakko",
        "category": "Tools & Test",
        "price_aud": 12.0,
        "inventory": 420,
        "description": "Precision ground blades cut leads up to 16AWG with an angled head ideal for PCB trimming.",
        "image_path": "img/products/hakko-chp-170.jpg",
        "product_url": "https://www.hakko.com/english/products/hakko_chp170.html",
    },
    {
        "sku": "TOOLS-SPARKFUN-THIRDHAND",
        "name": "SparkFun Third Hand Kit",
        "brand": "SparkFun",
        "category": "Tools & Test",
        "price_aud": 38.0,
        "inventory": 118,
        "description": "A weighted base with articulating arms, alligator clips, and silicone covers holds boards steady for soldering and inspection.",
        "image_path": "img/products/sparkfun-third-hand-kit.jpg",
        "product_url": "https://www.sparkfun.com/products/13190",
    },
    {
        "sku": "TOOLS-PANAVISE-201JR",
        "name": "PanaVise 201 Junior Mini Vise",
        "brand": "PanaVise",
        "category": "Tools & Test",
        "price_aud": 79.0,
        "inventory": 52,
        "description": "Multipurpose vise with nylon jaws, 360° rotation, and tilting action perfect for PCB rework and camera fixtures.",
        "image_path": "img/products/panavise-201jr.jpg",
        "product_url": "https://www.panavise.com/index.html?pageID=1&page=vise&modelID=201",
    },
    {
        "sku": "PWR-ANKER-737-POWERBANK",
        "name": "Anker 737 Power Bank (PowerCore 24K)",
        "brand": "Anker",
        "category": "Power & Batteries",
        "price_aud": 319.0,
        "inventory": 60,
        "description": "A 24,000mAh pack with dual USB-C ports delivering up to 140W PD, perfect for field laptops and SBC clusters.",
        "image_path": "img/products/anker-737-power-bank.jpg",
        "product_url": "https://www.anker.com/products/a1289",
    },
    {
        "sku": "PWR-ECOFLOW-DELTA2",
        "name": "EcoFlow DELTA 2 Portable Power Station",
        "brand": "EcoFlow",
        "category": "Power & Batteries",
        "price_aud": 1699.0,
        "inventory": 18,
        "description": "1024Wh LFP battery with 1800W AC inverter, X-Stream fast charging, and app monitoring for pop-up labs.",
        "image_path": "img/products/ecoflow-delta-2.jpg",
        "product_url": "https://www.ecoflow.com/au/delta-2-portable-power-station",
    },
    {
        "sku": "PWR-GOALZERO-SHERPA100AC",
        "name": "Goal Zero Sherpa 100AC Power Bank",
        "brand": "Goal Zero",
        "category": "Power & Batteries",
        "price_aud": 549.0,
        "inventory": 24,
        "description": "A travel-friendly 100Wh pack with 60W USB-C PD, 100W AC inverter, and Qi wireless pad for photography and field instrumentation teams.",
        "image_path": "img/products/goalzero-sherpa-100ac.jpg",
        "product_url": "https://www.goalzero.com/products/sherpa-100ac-power-bank",
    },
    {
        "sku": "PWR-DJI-MAVIC3-BATTERY",
        "name": "DJI Mavic 3 Intelligent Flight Battery",
        "brand": "DJI",
        "category": "Power & Batteries",
        "price_aud": 319.0,
        "inventory": 35,
        "description": "A 5000mAh battery delivering up to 46 minutes of flight time with smart telemetry for DJI's flagship mapping drone.",
        "image_path": "img/products/dji-mavic3-intelligent-battery.jpg",
        "product_url": "https://store.dji.com/au/product/mavic-3-intelligent-flight-battery",
    },
    {
        "sku": "PWR-MEANWELL-LRS350-24",
        "name": "Mean Well LRS-350-24 Power Supply",
        "brand": "Mean Well",
        "category": "Power & Batteries",
        "price_aud": 89.0,
        "inventory": 70,
        "description": "24V, 14.6A industrial PSU with adjustable output and short-circuit protection for LED walls and motion rigs.",
        "image_path": "img/products/meanwell-lrs-350-24.jpg",
        "product_url": "https://www.meanwell.com/productPdf.aspx?i=772",
    },
    {
        "sku": "PWR-TATTU-RLINE-1300-6S",
        "name": "Tattu R-Line 1300mAh 6S 150C LiPo",
        "brand": "Tattu",
        "category": "Power & Batteries",
        "price_aud": 129.0,
        "inventory": 48,
        "description": "High-discharge pack with XT60 connector built for FPV drones needing 150C bursts without voltage sag.",
        "image_path": "img/products/tattu-rline-1300-6s.jpg",
        "product_url": "https://www.genstattu.com/tattu-r-line-1300mah-150c-22-2v-6s1p-li-po-battery-pack-with-xr-plug.html",
    },
    {
        "sku": "PWR-BIOENNO-BLF1212A",
        "name": "Bioenno Power BLF-1212A LiFePO4 Battery",
        "brand": "Bioenno Power",
        "category": "Power & Batteries",
        "price_aud": 269.0,
        "inventory": 26,
        "description": "12V 12Ah LiFePO4 pack with Anderson Powerpole leads and built-in BMS for solar, ham radio, and remote instrumentation.",
        "image_path": "img/products/bioenno-blf-1212a.jpg",
        "product_url": "https://www.bioennopower.com/collections/12v-series-lifepo4-batteries/products/blf-1212a",
    },
    {
        "sku": "PWR-ADAFRUIT-USBC-LIPO-CHARGER",
        "name": "Adafruit USB-C LiIon/LiPoly Charger (MCP73833)",
        "brand": "Adafruit",
        "category": "Power & Batteries",
        "price_aud": 22.0,
        "inventory": 190,
        "description": "500mA charge controller with USB-C input, JST-PH output, and status LEDs for custom battery-powered builds.",
        "image_path": "img/products/adafruit-usbc-lipo-charger.jpg",
        "product_url": "https://www.adafruit.com/product/4755",
    },
    {
        "sku": "PWR-SPARKFUN-SUNNY-BUDDY",
        "name": "SparkFun Sunny Buddy MPPT Solar Charger",
        "brand": "SparkFun",
        "category": "Power & Batteries",
        "price_aud": 75.0,
        "inventory": 52,
        "description": "MPPT charger for 6V solar panels and LiPo packs with adjustable current limiting for remote sensor deployments.",
        "image_path": "img/products/sparkfun-sunny-buddy.jpg",
        "product_url": "https://www.sparkfun.com/products/15217",
    },
    {
        "sku": "PWR-POWERWERX-SS30DV",
        "name": "Powerwerx SS-30DV Desktop Power Supply",
        "brand": "Powerwerx",
        "category": "Power & Batteries",
        "price_aud": 299.0,
        "inventory": 19,
        "description": "30A continuous/35A surge switching supply with Powerpole outputs and variable 5-16V range for radio and robotics benches.",
        "image_path": "img/products/powerwerx-ss30dv.jpg",
        "product_url": "https://powerwerx.com/ss-30dv-desktop-dc-power-supply",
    },
    {
        "sku": "DISP-DELL-U2723QE",
        "name": "Dell UltraSharp U2723QE 4K Monitor",
        "brand": "Dell",
        "category": "Audio & Displays",
        "price_aud": 1249.0,
        "inventory": 20,
        "description": "27-inch IPS Black panel with 4K resolution, 98% DCI-P3, Thunderbolt-style USB-C hub, and RJ45 networking for single-cable desk setups.",
        "image_path": "img/products/dell-ultrasharp-u2723qe.jpg",
        "product_url": "https://www.dell.com/en-au/shop/dell-ultrasharp-27-4k-usb-c-hub-monitor-u2723qe/apd/210-bczx/monitors-monitor-accessories",
    },
    {
        "sku": "DISP-LG-27GP850-B",
        "name": "LG UltraGear 27GP850-B",
        "brand": "LG",
        "category": "Audio & Displays",
        "price_aud": 799.0,
        "inventory": 42,
        "description": "27-inch Nano IPS panel with QHD 165Hz (180Hz OC), 1ms GtG, and NVIDIA G-SYNC Compatible certification for sim labs.",
        "image_path": "img/products/lg-ultragear-27gp850-b.jpg",
        "product_url": "https://www.lg.com/au/monitors/lg-27gp850-b",
    },
    {
        "sku": "DISP-ASUS-PA278CV",
        "name": "ASUS ProArt Display PA278CV",
        "brand": "ASUS",
        "category": "Audio & Displays",
        "price_aud": 699.0,
        "inventory": 37,
        "description": "Factory-calibrated WQHD IPS panel covering 100% sRGB/Rec.709 with USB-C 65W power delivery for studio laptops.",
        "image_path": "img/products/asus-proart-pa278cv.jpg",
        "product_url": "https://www.asus.com/displays-desktops/monitors/proart/proart-display-pa278cv/",
    },
    {
        "sku": "DISP-BENQ-PD3220U",
        "name": "BenQ PD3220U 32\" 4K Monitor",
        "brand": "BenQ",
        "category": "Audio & Displays",
        "price_aud": 1999.0,
        "inventory": 15,
        "description": "Thunderbolt 3 monitor with 95% P3 coverage, dual-color modes, and KVM for calibrating render nodes.",
        "image_path": "img/products/benq-pd3220u.jpg",
        "product_url": "https://www.benq.com/en-au/monitor/designer/pd3220u.html",
    },
    {
        "sku": "AUDIO-AUDIOENGINE-A5PLUS",
        "name": "Audioengine A5+ Wireless Speakers",
        "brand": "Audioengine",
        "category": "Audio & Displays",
        "price_aud": 799.0,
        "inventory": 28,
        "description": "Class A/B amplifiers pushing 150W peak power with aptX HD Bluetooth and RCA inputs for desktop studios.",
        "image_path": "img/products/audioengine-a5-plus-wireless.jpg",
        "product_url": "https://audioengine.com/product_tech_specs/a5-wireless-speakers/",
    },
    {
        "sku": "AUDIO-JBL-305P-MKII",
        "name": "JBL 305P MkII Powered Monitor",
        "brand": "JBL Professional",
        "category": "Audio & Displays",
        "price_aud": 299.0,
        "inventory": 60,
        "description": "5-inch powered studio monitor with Image Control Waveguide for accurate imaging in edit suites.",
        "image_path": "img/products/jbl-305p-mkii.jpg",
        "product_url": "https://jblpro.com/en/products/305p-mkii",
    },
    {
        "sku": "AUDIO-PRESONUS-ERIS-E5XT",
        "name": "PreSonus Eris E5 XT Studio Monitor",
        "brand": "PreSonus",
        "category": "Audio & Displays",
        "price_aud": 339.0,
        "inventory": 44,
        "description": "Waveguide-tuned 5.25\" monitor with acoustic tuning switches ideal for small control rooms.",
        "image_path": "img/products/presonus-eris-e5-xt.jpg",
        "product_url": "https://www.presonus.com/en-US/ers-e5-xt.html",
    },
    {
        "sku": "AUDIO-SHURE-MV7",
        "name": "Shure MV7 Podcast Microphone",
        "brand": "Shure",
        "category": "Audio & Displays",
        "price_aud": 449.0,
        "inventory": 52,
        "description": "Dynamic mic with hybrid USB/XLR outputs, touch controls, and Voice Isolation for hybrid broadcast setups.",
        "image_path": "img/products/shure-mv7.jpg",
        "product_url": "https://www.shure.com/en-APAC/products/microphones/mv7",
    },
    {
        "sku": "AUDIO-RODE-NTUSBPLUS",
        "name": "RØDE NT-USB+",
        "brand": "RØDE",
        "category": "Audio & Displays",
        "price_aud": 289.0,
        "inventory": 65,
        "description": "Updated NT-USB with Revolution Preamp, 24-bit/96kHz capture, and built-in DSP for plug-and-play voiceovers.",
        "image_path": "img/products/rode-nt-usb-plus.jpg",
        "product_url": "https://rode.com/en/microphones/usb/nt-usb-plus",
    },
    {
        "sku": "AUDIO-ELGATO-WAVE-XLR",
        "name": "Elgato Wave XLR",
        "brand": "Elgato",
        "category": "Audio & Displays",
        "price_aud": 279.0,
        "inventory": 57,
        "description": "Compact USB-C audio interface with 75dB of gain, capacitive mute, and Clipguard for creator workstations.",
        "image_path": "img/products/elgato-wave-xlr.jpg",
        "product_url": "https://www.elgato.com/en/wave-xlr",
    },
    {
        "sku": "MAKER-ADAFRUIT-NEOPIXEL-RGBW-60",
        "name": "Adafruit NeoPixel RGBW LED Strip 60/m (1m)",
        "brand": "Adafruit",
        "category": "Maker Parts",
        "price_aud": 54.0,
        "inventory": 120,
        "description": "60 RGBW LEDs per metre with warm white channel and adhesive backing for lighting rigs driven by CircuitPython or Arduino.",
        "image_path": "img/products/adafruit-neopixel-rgbw-strip.jpg",
        "product_url": "https://www.adafruit.com/product/2847",
    },
    {
        "sku": "MAKER-SPARKFUN-BME688",
        "name": "SparkFun Environmental Combo Breakout (BME688)",
        "brand": "SparkFun",
        "category": "Maker Parts",
        "price_aud": 41.0,
        "inventory": 150,
        "description": "Bosch BME688 sensor measures temperature, humidity, pressure, and VOC gas with Qwiic connector for rapid prototyping.",
        "image_path": "img/products/sparkfun-bme688-breakout.jpg",
        "product_url": "https://www.sparkfun.com/products/19032",
    },
    {
        "sku": "MAKER-ADAFRUIT-BNO085",
        "name": "Adafruit BNO085 Orientation Sensor Breakout",
        "brand": "Adafruit",
        "category": "Maker Parts",
        "price_aud": 49.0,
        "inventory": 86,
        "description": "9-DoF sensor fusion with the BNO085 IMU delivers absolute orientation over I2C/SPI with STEMMA QT connectors.",
        "image_path": "img/products/adafruit-bno085-breakout.jpg",
        "product_url": "https://www.adafruit.com/product/4754",
    },
    {
        "sku": "MAKER-POLOLU-A4988",
        "name": "Pololu A4988 Stepper Motor Driver Carrier",
        "brand": "Pololu",
        "category": "Maker Parts",
        "price_aud": 18.0,
        "inventory": 190,
        "description": "Popular carrier board with microstepping up to 1/16 step and adjustable current limiting for 3D printers and CNC upgrades.",
        "image_path": "img/products/pololu-a4988-driver.jpg",
        "product_url": "https://www.pololu.com/product/1182",
    },
    {
        "sku": "MAKER-SEEED-GROVE-GPS",
        "name": "Seeed Studio Grove - GPS Module",
        "brand": "Seeed Studio",
        "category": "Maker Parts",
        "price_aud": 32.0,
        "inventory": 130,
        "description": "u-blox NEO-6M GPS breakout with Grove connector and super-cap backup for logging location data effortlessly.",
        "image_path": "img/products/seeed-grove-gps-module.jpg",
        "product_url": "https://www.seeedstudio.com/Grove-GPS-Module.html",
    },
    {
        "sku": "MAKER-ADAFRUIT-PERMAPROTO-HALF",
        "name": "Adafruit Perma-Proto Half-size Breadboard PCB",
        "brand": "Adafruit",
        "category": "Maker Parts",
        "price_aud": 9.0,
        "inventory": 260,
        "description": "Gold-plated pads follow the classic breadboard layout, letting prototypes graduate to permanent builds without rerouting.",
        "image_path": "img/products/adafruit-perma-proto-half.jpg",
        "product_url": "https://www.adafruit.com/product/1609",
    },
    {
        "sku": "MAKER-SPARKFUN-HX711",
        "name": "SparkFun Load Cell Amplifier - HX711",
        "brand": "SparkFun",
        "category": "Maker Parts",
        "price_aud": 16.0,
        "inventory": 180,
        "description": "Dual-channel 24-bit ADC breakout designed for Wheatstone bridge load cells and force experiments.",
        "image_path": "img/products/sparkfun-hx711-load-cell.jpg",
        "product_url": "https://www.sparkfun.com/products/13879",
    },
    {
        "sku": "MAKER-ADAFRUIT-VL53L4CD",
        "name": "Adafruit VL53L4CD Time-of-Flight Sensor",
        "brand": "Adafruit",
        "category": "Maker Parts",
        "price_aud": 24.0,
        "inventory": 145,
        "description": "ST's tiny ToF sensor measures distances up to 130cm with 1mm resolution over I2C and STEMMA QT cables.",
        "image_path": "img/products/adafruit-vl53l4cd-tof.jpg",
        "product_url": "https://www.adafruit.com/product/5396",
    },
    {
        "sku": "MAKER-POLOLU-DRV8835",
        "name": "Pololu DRV8835 Dual Motor Driver Carrier",
        "brand": "Pololu",
        "category": "Maker Parts",
        "price_aud": 17.0,
        "inventory": 173,
        "description": "Drives two DC motors up to 1.5A each from 2-11V with phase/enable or PWM inputs for combat bots and sumo minis.",
        "image_path": "img/products/pololu-drv8835-driver.jpg",
        "product_url": "https://www.pololu.com/product/2135",
    },
    {
        "sku": "MAKER-ADAFRUIT-MCP4725",
        "name": "Adafruit MCP4725 I2C DAC Breakout",
        "brand": "Adafruit",
        "category": "Maker Parts",
        "price_aud": 11.0,
        "inventory": 210,
        "description": "12-bit DAC with I2C interface and EEPROM for setting default output voltage in analog control projects.",
        "image_path": "img/products/adafruit-mcp4725-dac.jpg",
        "product_url": "https://www.adafruit.com/product/935",
    },
    {
        "sku": "MAKER-SPARKFUN-QWIIC-RELAY",
        "name": "SparkFun Qwiic Single Relay",
        "brand": "SparkFun",
        "category": "Maker Parts",
        "price_aud": 28.0,
        "inventory": 110,
        "description": "Control 10A loads over I2C using the Qwiic ecosystem, complete with status LEDs and address jumpers.",
        "image_path": "img/products/sparkfun-qwiic-relay.jpg",
        "product_url": "https://www.sparkfun.com/products/15336",
    },
    {
        "sku": "MAKER-ADAFRUIT-INA260",
        "name": "Adafruit INA260 High/Low Side Current Sensor",
        "brand": "Adafruit",
        "category": "Maker Parts",
        "price_aud": 29.0,
        "inventory": 132,
        "description": "A precision current and power monitor with integrated 2mΩ shunt and STEMMA QT connectors for monitoring supply rails.",
        "image_path": "img/products/adafruit-ina260-sensor.jpg",
        "product_url": "https://www.adafruit.com/product/4226",
    },
    {
        "sku": "MAKER-SEEED-I2C-HUB-6PORT",
        "name": "Seeed Studio Grove - I2C Hub (6 Port)",
        "brand": "Seeed Studio",
        "category": "Maker Parts",
        "price_aud": 14.0,
        "inventory": 160,
        "description": "Expands a single Grove I2C port into six connectors for clean daisy-chaining of sensors.",
        "image_path": "img/products/seeed-grove-i2c-hub-6port.jpg",
        "product_url": "https://www.seeedstudio.com/Grove-I2C-Hub-6-Port-p-2896.html",
    },
    {
        "sku": "MAKER-SPARKFUN-OPENLOG-ARTEMIS",
        "name": "SparkFun OpenLog Artemis",
        "brand": "SparkFun",
        "category": "Maker Parts",
        "price_aud": 95.0,
        "inventory": 58,
        "description": "Battery-friendly data logger with Apollo3 microcontroller, built-in IMU, and auto-detecting Qwiic logging.",
        "image_path": "img/products/sparkfun-openlog-artemis.jpg",
        "product_url": "https://www.sparkfun.com/products/16445",
    },
    {
        "sku": "MAKER-ADAFRUIT-FEATHERWING-PROTO",
        "name": "Adafruit FeatherWing Proto",
        "brand": "Adafruit",
        "category": "Maker Parts",
        "price_aud": 11.0,
        "inventory": 205,
        "description": "A prototyping FeatherWing with plated through-holes and power rails for custom circuits on Feather boards.",
        "image_path": "img/products/adafruit-featherwing-proto.jpg",
        "product_url": "https://www.adafruit.com/product/2884",
    },
]
